apiVersion: v2
name: ticketowl
description: TicketOwl — Ticket Management Portal for the NightOwl Platform
type: application
version: 0.1.4
appVersion: "0.1.4"
maintainers:
  - name: Wisbric
    url: https://wisbric.com
keywords:
  - ticketing
  - support
  - sla
  - nightowl
