{{- if .Values.seed.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ticketowl.fullname" . }}-seed
  labels:
    {{- include "ticketowl.labels" . | nindent 4 }}
    app.kubernetes.io/component: seed
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 6
  template:
    metadata:
      labels:
        {{- include "ticketowl.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: seed
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ticketowl.serviceAccountName" . }}
      restartPolicy: Never
      containers:
        - name: seed
          image: {{ include "ticketowl.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: APP_MODE
              value: seed
            {{- include "ticketowl.commonEnv" . | nindent 12 }}
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
{{- end }}
