{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ticketowl.fullname" . }}
  labels:
    {{- include "ticketowl.labels" . | nindent 4 }}
type: Opaque
stringData:
  TICKETOWL_DB_URL: {{ .Values.secrets.dbUrl | quote }}
  TICKETOWL_REDIS_URL: {{ .Values.secrets.redisUrl | quote }}
  TICKETOWL_OIDC_ISSUER: {{ .Values.secrets.oidcIssuer | quote }}
  TICKETOWL_OIDC_CLIENT_ID: {{ .Values.secrets.oidcClientId | quote }}
  TICKETOWL_ENCRYPTION_KEY: {{ .Values.secrets.encryptionKey | quote }}
  TICKETOWL_NIGHTOWL_API_KEY: {{ .Values.secrets.nightowlApiKey | quote }}
  TICKETOWL_BOOKOWL_API_KEY: {{ .Values.secrets.bookowlApiKey | quote }}
{{- end }}
