// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ArticleLink struct {
	ID           uuid.UUID `json:"id"`
	TicketMetaID uuid.UUID `json:"ticket_meta_id"`
	ArticleID    uuid.UUID `json:"article_id"`
	ArticleSlug  string    `json:"article_slug"`
	ArticleTitle string    `json:"article_title"`
	LinkedBy     uuid.UUID `json:"linked_by"`
	CreatedAt    time.Time `json:"created_at"`
}

type AuditLog struct {
	ID           uuid.UUID       `json:"id"`
	ActorID      pgtype.UUID     `json:"actor_id"`
	ActorName    *string         `json:"actor_name"`
	Action       string          `json:"action"`
	ResourceType string          `json:"resource_type"`
	ResourceID   string          `json:"resource_id"`
	Metadata     json.RawMessage `json:"metadata"`
	CreatedAt    time.Time       `json:"created_at"`
}

type AutoTicketRule struct {
	ID              uuid.UUID `json:"id"`
	Name            string    `json:"name"`
	Enabled         bool      `json:"enabled"`
	AlertGroup      *string   `json:"alert_group"`
	MinSeverity     *string   `json:"min_severity"`
	DefaultPriority string    `json:"default_priority"`
	DefaultGroup    *string   `json:"default_group"`
	TitleTemplate   string    `json:"title_template"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type CustomerOrg struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	OidcGroup   string    `json:"oidc_group"`
	ZammadOrgID *int32    `json:"zammad_org_id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type GlobalApiKey struct {
	ID          uuid.UUID          `json:"id"`
	TenantID    uuid.UUID          `json:"tenant_id"`
	KeyHash     string             `json:"key_hash"`
	Description string             `json:"description"`
	CreatedAt   time.Time          `json:"created_at"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
}

type GlobalTenant struct {
	ID        uuid.UUID `json:"id"`
	Slug      string    `json:"slug"`
	Name      string    `json:"name"`
	Suspended bool      `json:"suspended"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type IncidentLink struct {
	ID           uuid.UUID `json:"id"`
	TicketMetaID uuid.UUID `json:"ticket_meta_id"`
	IncidentID   uuid.UUID `json:"incident_id"`
	IncidentSlug string    `json:"incident_slug"`
	LinkedBy     uuid.UUID `json:"linked_by"`
	CreatedAt    time.Time `json:"created_at"`
}

type IntegrationKey struct {
	ID        uuid.UUID `json:"id"`
	Service   string    `json:"service"`
	ApiKey    string    `json:"api_key"`
	ApiUrl    string    `json:"api_url"`
	UpdatedAt time.Time `json:"updated_at"`
}

type InternalNote struct {
	ID           uuid.UUID `json:"id"`
	TicketMetaID uuid.UUID `json:"ticket_meta_id"`
	AuthorID     uuid.UUID `json:"author_id"`
	AuthorName   string    `json:"author_name"`
	Body         string    `json:"body"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type PostmortemLink struct {
	ID            uuid.UUID `json:"id"`
	TicketMetaID  uuid.UUID `json:"ticket_meta_id"`
	PostmortemID  uuid.UUID `json:"postmortem_id"`
	PostmortemUrl string    `json:"postmortem_url"`
	CreatedBy     uuid.UUID `json:"created_by"`
	CreatedAt     time.Time `json:"created_at"`
}

type SlaPolicy struct {
	ID                uuid.UUID      `json:"id"`
	Name              string         `json:"name"`
	Priority          string         `json:"priority"`
	ResponseMinutes   int32          `json:"response_minutes"`
	ResolutionMinutes int32          `json:"resolution_minutes"`
	WarningThreshold  pgtype.Numeric `json:"warning_threshold"`
	IsDefault         bool           `json:"is_default"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}

type SlaState struct {
	ID                   uuid.UUID          `json:"id"`
	TicketMetaID         uuid.UUID          `json:"ticket_meta_id"`
	ResponseDueAt        pgtype.Timestamptz `json:"response_due_at"`
	ResolutionDueAt      pgtype.Timestamptz `json:"resolution_due_at"`
	ResponseMetAt        pgtype.Timestamptz `json:"response_met_at"`
	FirstBreachAlertedAt pgtype.Timestamptz `json:"first_breach_alerted_at"`
	State                string             `json:"state"`
	Paused               bool               `json:"paused"`
	PausedAt             pgtype.Timestamptz `json:"paused_at"`
	AccumulatedPauseSecs int32              `json:"accumulated_pause_secs"`
	UpdatedAt            time.Time          `json:"updated_at"`
}

type TicketMetum struct {
	ID           uuid.UUID   `json:"id"`
	ZammadID     int32       `json:"zammad_id"`
	ZammadNumber string      `json:"zammad_number"`
	SlaPolicyID  pgtype.UUID `json:"sla_policy_id"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type User struct {
	ID          uuid.UUID `json:"id"`
	ExternalID  string    `json:"external_id"`
	Email       string    `json:"email"`
	DisplayName string    `json:"display_name"`
	Role        string    `json:"role"`
	IsActive    bool      `json:"is_active"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type ZammadConfig struct {
	ID            uuid.UUID   `json:"id"`
	Url           string      `json:"url"`
	ApiToken      string      `json:"api_token"`
	WebhookSecret string      `json:"webhook_secret"`
	PauseStatuses []string    `json:"pause_statuses"`
	UpdatedAt     time.Time   `json:"updated_at"`
	UpdatedBy     pgtype.UUID `json:"updated_by"`
}
