// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (GlobalApiKey, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (GlobalTenant, error)
	DeleteTenant(ctx context.Context, id uuid.UUID) error
	GetAPIKeyByHash(ctx context.Context, keyHash string) (GlobalApiKey, error)
	GetTenant(ctx context.Context, id uuid.UUID) (GlobalTenant, error)
	GetTenantBySlug(ctx context.Context, slug string) (GlobalTenant, error)
	GetUserByExternalID(ctx context.Context, externalID string) (User, error)
	ListTenants(ctx context.Context) ([]GlobalTenant, error)
	UpdateAPIKeyLastUsed(ctx context.Context, id uuid.UUID) error
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
